[package]
name = "kataradb"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.30"
crossbeam-channel = "0.5.8"
lazy_static = "1.4.0"
libc = "0.2.148"
rand = "0.8.5"
scopeguard = "1.2.0"
signal-hook = "0.3.17"
